# Generated by Django 4.2.1 on 2023-05-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_post_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
