# Generated by Django 4.2.1 on 2023-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_tag_posttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
    ]
